In [119]:
import pandas as pd
import requests
from io import StringIO

# Data Retrieval

In [120]:
import pandas as pd
import glob
import requests
from io import StringIO

# NGER（多文件 + 年份）
files = glob.glob("nger/*.csv")

year_map = {
    "ID0075": 2015,
    "ID0076": 2016,
    "ID0077": 2017,
    "ID0078": 2018,
    "ID0079": 2019,
    "ID0080": 2020,
    "ID0081": 2021,
    "ID0082": 2022,
    "ID0083": 2023,
    "ID0084": 2024,
}

df_list = []
for f in files:
    df = pd.read_csv(f)
    file_id = f.split("NGER.")[-1].replace(".csv", "")
    df["year"] = year_map.get(file_id, None)
    df_list.append(df)

df_nger = pd.concat(df_list, ignore_index=True)

# CER（三个表）
df_accredited = pd.read_csv("power-stations-and-projects-accredited.csv")
df_committed = pd.read_csv("power-stations-and-projects-committed.csv")
df_probable = pd.read_csv("power-stations-and-projects-probable.csv")

# ABS（API）
abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_REMOTENESS_ASGS2021,1.4.0/POP+ERP+ERP_P_20+ERP_21+ERP_M_20+ERP_F_20+ERP_19+ERP_22+ERP_23+ERP_18+ERP_17+ERP_M_1+ERP_M_2+ERP_M_3+ERP_M_4+ERP_M_5+ERP_M_6+ERP_M_7+ERP_M_8+ERP_M_9+ERP_M_10+ERP_M_11+ERP_M_12+ERP_M_13+ERP_M_14+ERP_M_15+ERP_M_16+ERP_M_17+ERP_M_18+ERP_M_19+ERP_M_21+ERP_M_22+ERP_M_23+ERP_M_24+ERP_M_25+ERP_M_26+ERP_M_27+ERP_M_28+ERP_M_29+ERP_M_30+ERP_M_31+ERP_M_32+ERP_M_33+ERP_M_34+ERP_M_35+ERP_M_36+ERP_M_37+ERP_M_38+ERP_F_1+ERP_F_2+ERP_F_3+ERP_F_4+ERP_F_5+ERP_F_6+ERP_F_7+ERP_F_8+ERP_F_9+ERP_F_10+ERP_F_11+ERP_F_12+ERP_F_13+ERP_F_14+ERP_F_15+ERP_F_16+ERP_F_17+ERP_F_18+ERP_F_19+ERP_F_21+ERP_F_22+ERP_F_23+ERP_F_24+ERP_F_25+ERP_F_26+ERP_F_27+ERP_F_28+ERP_F_29+ERP_F_30+ERP_F_31+ERP_F_32+ERP_F_33+ERP_F_34+ERP_F_35+ERP_F_36+ERP_F_37+ERP_F_38+ERP_P_1+ERP_P_2+ERP_P_3+ERP_P_4+ERP_P_5+ERP_P_6+ERP_P_7+ERP_P_8+ERP_P_9+ERP_P_10+ERP_P_11+ERP_P_12+ERP_P_13+ERP_P_14+ERP_P_15+ERP_P_16+ERP_P_17+ERP_P_18+ERP_P_19+ERP_P_21+ERP_P_22+ERP_P_23+ERP_P_24+ERP_P_25+ERP_P_26+ERP_P_27+ERP_P_28+ERP_P_29+ERP_P_30+ERP_P_31+ERP_P_32+ERP_P_33+ERP_P_34+ERP_P_35+ERP_P_36+ERP_P_37+ERP_P_38+BD_1+BD_2+BD_3+BD_4+BD_5+ING_POP+ING_ERP_5+ING_MA_M+ING_MA_F+ING_MA_P+ING_WA1+ING_WA2+ING_ERP_P+ING_ERP_M1+ING_M014+ING_M1524+ING_M2534+ING_M3544+ING_M4554+ING_M55OVER+ING_ERP_M+ING_ERP_F1+ING_F014+ING_F1524+ING_F2534+ING_F3544+ING_F4554+ING_F55OVER+ING_ERP_F+ING_ERP_P1+ING_P014+ING_P1524+ING_P2534+ING_P3544+ING_P4554+ING_P55OVER+ING_CLTID1+ING_CULTID+ING_HLTC1+ING_HLTC2+ING_HLTC3+ING_LANG+ING_LANG1+ING_LANG2+ING_EETPH+ING_EETP1+ING_EETP2+ING_EETP3+ING_LABFC+ING_EMP1+ING_EMP2+ING_UNEMP1+ING_UNEMP2+ING_LABF+ING_LFPR+ING_NILF+ING_1564+ING_EMP3+ING_UAH+ING_UA1+ING_UA2+ING_UPCC+ING_UPCC1+ING_UPCC2+ING_UPCC3+ING_UPCC4+ING_UPCC5+ING_UPCC6+ING_UPCC7+ING_UPCC8+ING_VOLWP+ING_VOLWP1+ING_VOLWP2+ING_HLTH1+ING_SAHLTH+ING_DISAB+ING_DISAB1+ING_DISAB2+ING_DISAB3+ING_DISAB4+ING_DISAB5+ING_DISAB6+ING_DISAB7+ING_LTHC+ING_LTHC1+ING_LTHC2+ING_LTHC3+ING_LTHC4+ING_LTHC5+ING_LTHC6+ING_USPH+ING_USP1+ING_USP2+ING_USP3+ING_USP4+ING_ALCH+ING_ALC1+ING_ALC2+ING_SMKH+ING_SMK1+ING_SMK2+ING_TTYPE+ING_TTYPE1+ING_TTYPE2+ING_TTYPE3+ING_TTYPE4+ING_HMLSS+ING_HMLSS1+ING_HMLSS2+ING_YR12C3P+ING_YR12C3P1+ING_YR12C3P2+ING_YR12C3P3+ING_HEAP+ING_HEAP1+ING_HEAP2+ING_HEAP3+ING_EETP+ING_EETPH1+ING_EETPH2+ING_EETPH3+ING_LFSP+ING_LFSP1+ING_LFSP2+ING_LFSP3+ING_HOSD+ING_HOSD1+ING_HOSD2+ING_HOSD3+ING_HOSD4+ING_HOSD5+ING_HOSD6+ING_HOSD7+ING_HOSD8+ING_HOSD9+ING_HOSD10+ING_HOSD11+INC+PENSION_1+PENSION_3+PENSION_4+PENSION_5+ENV+LAND_1+LAND..0+1+2+3+4+5+6+7+8+9+11+12+13+14+20+21+22+23+30+31+32+33+34+40+41+42+43+44+50+51+52+53+54+61+62+63+64+72+73+74+80+81+91+94+10.A?startPeriod=2012&endPeriod=2024&dimensionAtObservation=AllDimensions"
# abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_ASGS2021,/..1+2+3+4+5+6+7+8+9.A?startPeriod=2020&dimensionAtObservation=AllDimensions"


headers = {
    "Accept": "application/vnd.sdmx.data+csv;labels=both"
}

response = requests.get(abs_url, headers=headers, timeout=60)
response.raise_for_status()

df_abs = pd.read_csv(StringIO(response.text))

print(df_nger.shape)
print(df_accredited.shape, df_committed.shape, df_probable.shape)
print(df_abs.shape)

display(df_nger.head())
display(df_abs.head())

(5942, 33)
(36, 8) (36, 5) (59, 4)
(31766, 11)

,Reporting entity,Facility name,Type,State,Electricity production GJ,Electricity production MWh,Total scope 1 emissions t CO2 e,Total scope 2 emissions t CO2 e,Total emissions t CO2 e,Emission intensity t CO2 e MWh,...,Grid Connected,Primary Fuel,Important Notes,Controlling corporation,Electricity Production Mwh,Emission Intensity t Mwh,Total Scope 2 Emissions t CO2 e 2,Grid Connected2,Scope 1 t CO2 e,Scope 2 t CO2 e
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,555151.0,154209.0,50.0,95.0,145.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,636185.0,176718.0,45.0,143.0,188.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1086174.0,301715.0,49.0,308.0,357.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2414107.0,670585.0,139.0,452.0,591.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACCIONA ENERGY OCEANIA PTY LTD,Corporate Total,C,-,4691617.0,1303227.0,283.0,998.0,1281.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,DATAFLOW,MEASURE: Data Item,REGIONTYPE: Region Type,REGION: Region,FREQUENCY: Frequency,TIME_PERIOD: Time Period,OBS_VALUE,UNIT_MEASURE: Unit of Measure,UNIT_MULT: Unit of Multiplier,OBS_STATUS: Observation Status,OBS_COMMENT: Observation Comment
0,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2018,1.75,RATE: Rate,NaN,NaN,NaN
1,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2019,1.63,RATE: Rate,NaN,NaN,NaN
2,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2020,1.59,RATE: Rate,NaN,NaN,NaN
3,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2021,1.56,RATE: Rate,NaN,NaN,NaN
4,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2022,1.50,RATE: Rate,NaN,NaN,NaN

# Data Preprocessing

## clean NGER

## merge CER

In [121]:
# 1. 去掉列名空格
df_accredited.columns = df_accredited.columns.str.strip()
df_committed.columns = df_committed.columns.str.strip()
df_probable.columns = df_probable.columns.str.strip()

# 2. rename
df_accredited_full = df_accredited.rename(columns={
    "Power station name": "project_name",
    "State": "state",
    "Installed capacity (MW)": "capacity_mw",
    "Fuel Source (s)": "fuel_source",
    "Accreditation code": "accreditation_code",
    "Postcode": "postcode",
    "Accreditation start date": "accreditation_start_date",
    "Approval date": "approval_date"
})

df_committed_full = df_committed.rename(columns={
    "Project Name": "project_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source",
    "Committed Date (Month/Year)": "committed_date"
})

df_probable_full = df_probable.rename(columns={
    "Probable Projects": "project_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source"
})

# 3. concat（三个表一起）
df_cer = pd.concat(
    [df_accredited_full, df_committed_full, df_probable_full],
    ignore_index=True
)

# 4. 标记来源
df_cer.loc[df_cer["accreditation_code"].notna(), "project_status"] = "accredited"
df_cer.loc[df_cer["committed_date"].notna(), "project_status"] = "committed"

# probable（两列都为空）
df_cer.loc[
    df_cer["accreditation_code"].isna() & df_cer["committed_date"].isna(),
    "project_status"
] = "probable"

# 5. 查看结果
print(df_cer.head())
print(df_cer.info())

  accreditation_code                                       project_name state  \
0           SRPXQLO8                      DONS FORT - SOLAR W SGU - QLD   QLD
1           SRPYNSK0                    Mintus Coles - Solar w SGU- NSW   NSW
2           SRPXQLP1               Ventora - Acacia Ridge - Solar - QLD   QLD
3           SRPYNSK3         Bayside Aged Care - Solar - Morisset - NSW   NSW
4           SRPVWAQ0  Matrix Composites and Engineering Pty Ltd - So...    WA

   postcode capacity_mw fuel_source accreditation_start_date approval_date  \
0    4660.0       0.421       Solar               21/10/2025     6/01/2026
1    2153.0        0.19       Solar                9/12/2025     6/01/2026
2    4110.0       0.162       Solar               17/11/2025     6/01/2026
3    2264.0        0.14       Solar               16/12/2025     8/01/2026
4    6166.0        0.85       Solar               17/12/2025     8/01/2026

  committed_date project_status
0            NaN     accredited
1            NaN     accredited
2            NaN     accredited
3            NaN     accredited
4            NaN     accredited
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   accreditation_code        36 non-null     object
 1   project_name              131 non-null    object
 2   state                     131 non-null    object
 3   postcode                  36 non-null     float64
 4   capacity_mw               131 non-null    object
 5   fuel_source               131 non-null    object
 6   accreditation_start_date  36 non-null     object
 7   approval_date             36 non-null     object
 8   committed_date            36 non-null     object
 9   project_status            131 non-null    object
dtypes: float64(1), object(9)
memory usage: 10.4+ KB
None

In [122]:
# =========================
# NGER
# =========================
print("=== NGER shape ===")
print(df_nger.shape)

print("=== NGER columns ===")
display(df_nger.columns)

print("=== NGER head ===")
display(df_nger.head())


# =========================
# CER（你已经合并好的 df_cer）
# =========================
print("=== CER shape ===")
print(df_cer.shape)

print("=== CER columns ===")
display(df_cer.columns)

print("=== CER head ===")
display(df_cer.head())


# =========================
# ABS
# =========================
print("=== ABS shape ===")
print(df_abs.shape)

print("=== ABS columns ===")
display(df_abs.columns)

print("=== ABS head ===")
display(df_abs.head())

=== NGER shape ===
(5942, 33)
=== NGER columns ===

Index(['Reporting entity', 'Facility name', 'Type', 'State',
       'Electricity production GJ', 'Electricity production MWh',
       'Total scope 1 emissions t CO2 e', 'Total scope 2 emissions t CO2 e',
       'Total emissions t CO2 e', 'Emission intensity t CO2 e MWh',
       'Grid connected', 'Grid', 'Primary fuel', 'Important notes', 'year',
       'Reporting Entity', 'Facility Name', 'Electricity Production GJ',
       'Electricity Production MWh', 'Total Scope 1 Emissions t CO2 e',
       'Total Scope 2 Emissions t CO2 e', 'Total Emissions t CO2 e',
       'Emission Intensity t CO2 e MWh', 'Grid Connected', 'Primary Fuel',
       'Important Notes', 'Controlling corporation',
       'Electricity Production Mwh', 'Emission Intensity t Mwh',
       'Total Scope 2 Emissions t CO2 e 2', 'Grid Connected2',
       'Scope 1 t CO2 e', 'Scope 2 t CO2 e'],
      dtype='object')

=== NGER head ===

,Reporting entity,Facility name,Type,State,Electricity production GJ,Electricity production MWh,Total scope 1 emissions t CO2 e,Total scope 2 emissions t CO2 e,Total emissions t CO2 e,Emission intensity t CO2 e MWh,...,Grid Connected,Primary Fuel,Important Notes,Controlling corporation,Electricity Production Mwh,Emission Intensity t Mwh,Total Scope 2 Emissions t CO2 e 2,Grid Connected2,Scope 1 t CO2 e,Scope 2 t CO2 e
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,555151.0,154209.0,50.0,95.0,145.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,636185.0,176718.0,45.0,143.0,188.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1086174.0,301715.0,49.0,308.0,357.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2414107.0,670585.0,139.0,452.0,591.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACCIONA ENERGY OCEANIA PTY LTD,Corporate Total,C,-,4691617.0,1303227.0,283.0,998.0,1281.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

=== CER shape ===
(131, 10)
=== CER columns ===

Index(['accreditation_code', 'project_name', 'state', 'postcode',
       'capacity_mw', 'fuel_source', 'accreditation_start_date',
       'approval_date', 'committed_date', 'project_status'],
      dtype='object')

=== CER head ===

,accreditation_code,project_name,state,postcode,capacity_mw,fuel_source,accreditation_start_date,approval_date,committed_date,project_status
0,SRPXQLO8,DONS FORT - SOLAR W SGU - QLD,QLD,4660.0,0.421,Solar,21/10/2025,6/01/2026,NaN,accredited
1,SRPYNSK0,Mintus Coles - Solar w SGU- NSW,NSW,2153.0,0.19,Solar,9/12/2025,6/01/2026,NaN,accredited
2,SRPXQLP1,Ventora - Acacia Ridge - Solar - QLD,QLD,4110.0,0.162,Solar,17/11/2025,6/01/2026,NaN,accredited
3,SRPYNSK3,Bayside Aged Care - Solar - Morisset - NSW,NSW,2264.0,0.14,Solar,16/12/2025,8/01/2026,NaN,accredited
4,SRPVWAQ0,Matrix Composites and Engineering Pty Ltd - So...,WA,6166.0,0.85,Solar,17/12/2025,8/01/2026,NaN,accredited

=== ABS shape ===
(31766, 11)
=== ABS columns ===

Index(['DATAFLOW', 'MEASURE: Data Item', 'REGIONTYPE: Region Type',
       'REGION: Region', 'FREQUENCY: Frequency', 'TIME_PERIOD: Time Period',
       'OBS_VALUE', 'UNIT_MEASURE: Unit of Measure',
       'UNIT_MULT: Unit of Multiplier', 'OBS_STATUS: Observation Status',
       'OBS_COMMENT: Observation Comment'],
      dtype='object')

=== ABS head ===

,DATAFLOW,MEASURE: Data Item,REGIONTYPE: Region Type,REGION: Region,FREQUENCY: Frequency,TIME_PERIOD: Time Period,OBS_VALUE,UNIT_MEASURE: Unit of Measure,UNIT_MULT: Unit of Multiplier,OBS_STATUS: Observation Status,OBS_COMMENT: Observation Comment
0,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2018,1.75,RATE: Rate,NaN,NaN,NaN
1,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2019,1.63,RATE: Rate,NaN,NaN,NaN
2,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2020,1.59,RATE: Rate,NaN,NaN,NaN
3,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2021,1.56,RATE: Rate,NaN,NaN,NaN
4,ABS:ABS_REGIONAL_REMOTENESS_ASGS2021(1.4.0),BD_3: Total fertility rate (births per female)...,RA: Remoteness Area,61: Inner Regional Australia (Tas.),A: Annual,2022,1.50,RATE: Rate,NaN,NaN,NaN

In [123]:
import pandas as pd
import re

STOP_TOKENS = {
     "farm", "wind", "solar", "stage", "creek", "hill",
    "river", "lake", "park", "energy", "power", "project",
    "facility", "renewable", "generation", "station",
    "green", "hub", "the", "of"
}

def clean_name(x):
    if pd.isna(x):
        return ""
    x = str(x).lower().strip()
    x = re.sub(r"\b(nsw|qld|vic|wa|sa|tas|act|nt)\b", " ", x)
    x = re.sub(r"\b(pty ltd|pty|ltd)\b", " ", x)
    x = re.sub(r"[^a-z0-9]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x

def token_set(x):
    if not x:
        return set()
    return {t for t in x.split() if t not in STOP_TOKENS and not t.isdigit()}

df_nger["name_key"] = df_nger["Facility name"].apply(clean_name)
df_cer["name_key"] = df_cer["project_name"].apply(clean_name)

matches = []

for _, n_row in df_nger.iterrows():
    n_name = n_row["name_key"]
    n_state = n_row["State"]
    n_tokens = token_set(n_name)

    if not n_tokens:
        continue

    for _, c_row in df_cer.iterrows():
        c_name = c_row["name_key"]
        c_state = c_row["state"]
        c_tokens = token_set(c_name)

        if n_state != c_state:
            continue
        if not c_tokens:
            continue

        overlap = n_tokens & c_tokens

        if len(overlap) >= 1:
            matches.append({
                "nger_name": n_row["Facility name"],
                "cer_name": c_row["project_name"],
                "nger_key": n_name,
                "cer_key": c_name,
                "state": n_state,
                "shared_tokens": ", ".join(sorted(overlap)),
                "overlap_count": len(overlap)
            })

df_match = pd.DataFrame(matches)

print("=== 匹配结果示例 ===")
display(df_match.sort_values("overlap_count", ascending=False).head(20))

print("\n=== 匹配统计 ===")
print("NGER 总数:", len(df_nger))
print("CER 总数:", len(df_cer))
print("匹配对数:", len(df_match))

if len(df_match) > 0:
    print("匹配到的 NGER 数:", df_match["nger_name"].nunique())
    print("匹配到的 CER 数:", df_match["cer_name"].nunique())

=== 匹配结果示例 ===

,nger_name,cer_name,nger_key,cer_key,state,shared_tokens,overlap_count
87,Vales Point Power Station,Vales Point Solar Farm,vales point power station,vales point solar farm,NSW,"point, vales",2
106,Vales Point Power Station,Vales Point Solar Farm,vales point power station,vales point solar farm,NSW,"point, vales",2
133,New England Solar Farm,New England Solar Farm - Stage 2,new england solar farm,new england solar farm stage 2,NSW,"england, new",2
39,Vales Point Power Station,Vales Point Solar Farm,vales point power station,vales point solar farm,NSW,"point, vales",2
8,Vales Point Power Station,Vales Point Solar Farm,vales point power station,vales point solar farm,NSW,"point, vales",2
155,Vales Point Power Station,Vales Point Solar Farm,vales point power station,vales point solar farm,NSW,"point, vales",2
0,Hunter Valley Gas Turbines,Valley of the Winds,hunter valley gas turbines,valley of the winds,NSW,valley,1
118,Darling Downs Power Station,BC Murrumba Downs - Solar - QLD,darling downs power station,bc murrumba downs solar,QLD,downs,1
112,Kidston Solar One - Solar - Qld,Kidston Stage 3 Wind Project,kidston solar one solar,kidston stage 3 wind project,QLD,kidston,1
113,Port Lincoln Power Station,Bunge Port Giles - Solar - SA,port lincoln power station,bunge port giles solar,SA,port,1
114,Port Lincoln Power Station,Port Augusta Energy Park Stage 2,port lincoln power station,port augusta energy park stage 2,SA,port,1
115,Rockingham Renewable Energy Facility,East Rockingham Resource Recovery Facility,rockingham renewable energy facility,east rockingham resource recovery facility,WA,rockingham,1
116,VICTORIAN BIG BATTERY PTY LTD,Derby Solar Farm & Battery,victorian big battery,derby solar farm battery,VIC,battery,1
117,WESTERN DOWNS GREEN POWER HUB PTY LTD,BC Murrumba Downs - Solar - QLD,western downs green power hub,bc murrumba downs solar,QLD,downs,1
120,Mount Emerald Wind Farm,Mount Hopeful Wind Farm,mount emerald wind farm,mount hopeful wind farm,QLD,mount,1
119,Norseman Gold Power Station,St Ives Gold Solar Farm,norseman gold power station,st ives gold solar farm,WA,gold,1
110,Water Gardens Shopping Centre Solar Farm,Waverley Gardens - Solar w SGU - VIC,water gardens shopping centre solar farm,waverley gardens solar w sgu,VIC,gardens,1
121,Murchison Radio Astronomy Power Station and Di...,Matrix Composites and Engineering Pty Ltd - So...,murchison radio astronomy power station and di...,matrix composites and engineering solar,WA,and,1
122,Nullagine Power Station & Nullagine Distributi...,Nullagine Wind Farm,nullagine power station nullagine distribution...,nullagine wind farm,WA,nullagine,1
123,Woolnorth Studland Bay Wind Farm Pty Ltd,Bell Bay Wind Farm,woolnorth studland bay wind farm,bell bay wind farm,TAS,bay,1

=== 匹配统计 ===
NGER 总数: 5942
CER 总数: 131
匹配对数: 172
匹配到的 NGER 数: 40
匹配到的 CER 数: 30

In [124]:
df_abs.to_csv("abs_data.csv", index=False)