In [111]:
import pandas as pd
import requests
from io import StringIO

# Data Retrieval

In [112]:
import pandas as pd
import glob
import requests
from io import StringIO

files = glob.glob("nger/*.csv")

year_map = {
    "ID0075": 2015,
    "ID0076": 2016,
    "ID0077": 2017,
    "ID0078": 2018,
    "ID0079": 2019,
    "ID0080": 2020,
    "ID0081": 2021,
    "ID0082": 2022,
    "ID0083": 2023,
    "ID0084": 2024,
}

rename_map = {
    "Reporting entity": "Reporting Entity",
    "Facility name": "Facility Name",
    "Electricity production GJ": "Electricity Production GJ",
    "Electricity production MWh": "Electricity Production MWh",
    "Total scope 1 emissions t CO2 e": "Total Scope 1 Emissions t CO2 e",
    "Total scope 2 emissions t CO2 e": "Total Scope 2 Emissions t CO2 e",
    "Total emissions t CO2 e": "Total Emissions t CO2 e",
    "Emission intensity t CO2 e MWh": "Emission Intensity t CO2 e MWh",
    "Grid connected": "Grid Connected",
    "Primary fuel": "Primary Fuel",
    "Important notes": "Important Notes",
    "Electricity Production Mwh": "Electricity Production MWh",
    "Emission Intensity t Mwh": "Emission Intensity t CO2 e MWh",
    "Total Scope 2 Emissions t CO2 e 2": "Total Scope 2 Emissions t CO2 e",
    "Grid Connected2": "Grid Connected",
    "Scope 1 t CO2 e": "Total Scope 1 Emissions t CO2 e",
    "Scope 2 t CO2 e": "Total Scope 2 Emissions t CO2 e",
}

df_list = []

for f in files:
    df = pd.read_csv(f)
    df.columns = df.columns.str.strip()
    df = df.rename(columns=rename_map)

    file_id = f.split("NGER.")[-1].replace(".csv", "")
    df["year"] = year_map.get(file_id, None)

    df_list.append(df)

df_nger = pd.concat(df_list, ignore_index=True)

# CER（三个表）
df_accredited = pd.read_csv("power-stations-and-projects-accredited.csv")
df_committed = pd.read_csv("power-stations-and-projects-committed.csv")
df_probable = pd.read_csv("power-stations-and-projects-probable.csv")

# ABS（API）
abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_ASGS2021,1.4.0/POP+ERP+ERP_P_20+ERP_21+ERP_M_20+ERP_F_20+ERP_19+ERP_22+ERP_23+ERP_18+ERP_17+ERP_M_1+ERP_M_2+ERP_M_3+ERP_M_4+ERP_M_5+ERP_M_6+ERP_M_7+ERP_M_8+ERP_M_9+ERP_M_10+ERP_M_11+ERP_M_12+ERP_M_13+ERP_M_14+ERP_M_15+ERP_M_16+ERP_M_17+ERP_M_18+ERP_M_19+ERP_M_21+ERP_M_22+ERP_M_23+ERP_M_24+ERP_M_25+ERP_M_26+ERP_M_27+ERP_M_28+ERP_M_29+ERP_M_30+ERP_M_31+ERP_M_32+ERP_M_33+ERP_M_34+ERP_M_35+ERP_M_36+ERP_M_37+ERP_M_38+ERP_F_1+ERP_F_2+ERP_F_3+ERP_F_4+ERP_F_5+ERP_F_6+ERP_F_7+ERP_F_8+ERP_F_9+ERP_F_10+ERP_F_11+ERP_F_12+ERP_F_13+ERP_F_14+ERP_F_15+ERP_F_16+ERP_F_17+ERP_F_18+ERP_F_19+ERP_F_21+ERP_F_22+ERP_F_23+ERP_F_24+ERP_F_25+ERP_F_26+ERP_F_27+ERP_F_28+ERP_F_29+ERP_F_30+ERP_F_31+ERP_F_32+ERP_F_33+ERP_F_34+ERP_F_35+ERP_F_36+ERP_F_37+ERP_F_38+ERP_P_1+ERP_P_2+ERP_P_3+ERP_P_4+ERP_P_5+ERP_P_6+ERP_P_7+ERP_P_8+ERP_P_9+ERP_P_10+ERP_P_11+ERP_P_12+ERP_P_13+ERP_P_14+ERP_P_15+ERP_P_16+ERP_P_17+ERP_P_18+ERP_P_19+ERP_P_21+ERP_P_22+ERP_P_23+ERP_P_24+ERP_P_25+ERP_P_26+ERP_P_27+ERP_P_28+ERP_P_29+ERP_P_30+ERP_P_31+ERP_P_32+ERP_P_33+ERP_P_34+ERP_P_35+ERP_P_36+ERP_P_37+ERP_P_38+BD_1+BD_2+BD_3+BD_4+BD_5+ING_POP+ING_ERP_5+ING_MA_M+ING_MA_F+ING_MA_P+ING_WA1+ING_WA2+ING_ERP_P+ING_ERP_M1+ING_M014+ING_M1524+ING_M2534+ING_M3544+ING_M4554+ING_M55OVER+ING_ERP_M+ING_ERP_F1+ING_F014+ING_F1524+ING_F2534+ING_F3544+ING_F4554+ING_F55OVER+ING_ERP_F+ING_ERP_P1+ING_P014+ING_P1524+ING_P2534+ING_P3544+ING_P4554+ING_P55OVER+ING_CLTID1+ING_CULTID+ING_HLTC1+ING_HLTC2+ING_HLTC3+ING_LANG+ING_LANG1+ING_LANG2+ING_EETPH+ING_EETP1+ING_EETP2+ING_EETP3+ING_LABFC+ING_EMP1+ING_EMP2+ING_UNEMP1+ING_UNEMP2+ING_LABF+ING_LFPR+ING_NILF+ING_1564+ING_EMP3+ING_UAH+ING_UA1+ING_UA2+ING_UPCC+ING_UPCC1+ING_UPCC2+ING_UPCC3+ING_UPCC4+ING_UPCC5+ING_UPCC6+ING_UPCC7+ING_UPCC8+ING_VOLWP+ING_VOLWP1+ING_VOLWP2+ING_HLTH1+ING_SAHLTH+ING_DISAB+ING_DISAB1+ING_DISAB2+ING_DISAB3+ING_DISAB4+ING_DISAB5+ING_DISAB6+ING_DISAB7+ING_LTHC+ING_LTHC1+ING_LTHC2+ING_LTHC3+ING_LTHC4+ING_LTHC5+ING_LTHC6+ING_USPH+ING_USP1+ING_USP2+ING_USP3+ING_USP4+ING_ALCH+ING_ALC1+ING_ALC2+ING_SMKH+ING_SMK1+ING_SMK2+ING_TTYPE+ING_TTYPE1+ING_TTYPE2+ING_TTYPE3+ING_TTYPE4+ING_HMLSS+ING_HMLSS1+ING_HMLSS2+ING_YR12C3P+ING_YR12C3P1+ING_YR12C3P2+ING_YR12C3P3+ING_HEAP+ING_HEAP1+ING_HEAP2+ING_HEAP3+ING_EETP+ING_EETPH1+ING_EETPH2+ING_EETPH3+ING_LFSP+ING_LFSP1+ING_LFSP2+ING_LFSP3+ING_HOSD+ING_HOSD1+ING_HOSD2+ING_HOSD3+ING_HOSD4+ING_HOSD5+ING_HOSD6+ING_HOSD7+ING_HOSD8+ING_HOSD9+ING_HOSD10+ING_HOSD11+INC+PENSION_1+PENSION_3+PENSION_4+PENSION_5+ENV+LAND_1+LAND..0+1+2+3+4+5+6+7+8+9+11+12+13+14+20+21+22+23+30+31+32+33+34+40+41+42+43+44+50+51+52+53+54+61+62+63+64+72+73+74+80+81+91+94+10.A?startPeriod=2012&endPeriod=2024&dimensionAtObservation=AllDimensions"
# abs_url = "https://data.api.abs.gov.au/rest/data/ABS,ABS_REGIONAL_ASGS2021,/..1+2+3+4+5+6+7+8+9.A?startPeriod=2020&dimensionAtObservation=AllDimensions"


headers = {
    "Accept": "application/vnd.sdmx.data+csv;labels=both"
}

response = requests.get(abs_url, headers=headers, timeout=60)
response.raise_for_status()

df_abs = pd.read_csv(StringIO(response.text))

print(df_nger.shape)
print(df_accredited.shape, df_committed.shape, df_probable.shape)
print(df_abs.shape)

display(df_nger.head())
display(df_abs.head())

(5942, 16)
(36, 8) (36, 5) (59, 4)
(7117, 11)

,Reporting Entity,Facility Name,Type,State,Electricity Production GJ,Electricity Production MWh,Total Scope 1 Emissions t CO2 e,Total Scope 2 Emissions t CO2 e,Total Emissions t CO2 e,Emission Intensity t CO2 e MWh,Grid Connected,Grid,Primary Fuel,Important Notes,year,Controlling corporation
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,555151.0,154209.0,50.0,95.0,145,0.0,On,NEM,Wind,-,2020,NaN
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,636185.0,176718.0,45.0,143.0,188,0.0,On,NEM,Wind,-,2020,NaN
2,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1086174.0,301715.0,49.0,308.0,357,0.0,On,NEM,Wind,-,2020,NaN
3,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2414107.0,670585.0,139.0,452.0,591,0.0,On,NEM,Wind,-,2020,NaN
4,ACCIONA ENERGY OCEANIA PTY LTD,Corporate Total,C,-,4691617.0,1303227.0,283.0,998.0,1281,NaN,-,-,-,-,2020,NaN

,DATAFLOW,MEASURE: Data Item,REGIONTYPE: Region Type,ASGS_2021: Region,FREQUENCY: Frequency,TIME_PERIOD: Time Period,OBS_VALUE,UNIT_MEASURE: Unit of Measure,UNIT_MULT: Unit of Multiplier,OBS_STATUS: Observation Status,OBS_COMMENT: Observation Comment
0,ABS:ABS_REGIONAL_ASGS2021(1.4.0),LAND: Land area (ha),STE: States and Territories,6: Tasmania,A: Annual,2021,6801753.9,HA: Hectares,NaN,NaN,NaN
1,ABS:ABS_REGIONAL_ASGS2021(1.4.0),ERP_F_33: Estimated resident population:Female...,STE: States and Territories,4: South Australia,A: Annual,2019,6.2,PCT: Percent,NaN,NaN,NaN
2,ABS:ABS_REGIONAL_ASGS2021(1.4.0),ERP_F_33: Estimated resident population:Female...,STE: States and Territories,4: South Australia,A: Annual,2020,6.3,PCT: Percent,NaN,NaN,NaN
3,ABS:ABS_REGIONAL_ASGS2021(1.4.0),ERP_F_33: Estimated resident population:Female...,STE: States and Territories,4: South Australia,A: Annual,2021,6.4,PCT: Percent,NaN,NaN,NaN
4,ABS:ABS_REGIONAL_ASGS2021(1.4.0),ERP_F_33: Estimated resident population:Female...,STE: States and Territories,4: South Australia,A: Annual,2022,6.4,PCT: Percent,NaN,NaN,NaN

# Data Preprocessing

### merge CER

In [113]:
df_accredited.columns = df_accredited.columns.str.strip()
df_committed.columns = df_committed.columns.str.strip()
df_probable.columns = df_probable.columns.str.strip()

df_accredited_full = df_accredited.rename(columns={
    "Power station name": "facility_name",
    "State": "state",
    "Installed capacity (MW)": "capacity_mw",
    "Fuel Source (s)": "fuel_source",
    "Accreditation code": "accreditation_code",
    "Postcode": "postcode",
    "Accreditation start date": "accreditation_start_date",
    "Approval date": "approval_date"
}).copy()

df_accredited_full["committed_date"] = pd.NA
df_accredited_full["project_status"] = "accredited"

df_committed_full = df_committed.rename(columns={
    "Project Name": "facility_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source",
    "Committed Date (Month/Year)": "committed_date"
}).copy()

df_committed_full["accreditation_code"] = pd.NA
df_committed_full["postcode"] = pd.NA
df_committed_full["accreditation_start_date"] = pd.NA
df_committed_full["approval_date"] = pd.NA
df_committed_full["project_status"] = "committed"

df_probable_full = df_probable.rename(columns={
    "Probable Projects": "facility_name",
    "State": "state",
    "MW Capacity": "capacity_mw",
    "Fuel Source": "fuel_source"
}).copy()

df_probable_full["accreditation_code"] = pd.NA
df_probable_full["postcode"] = pd.NA
df_probable_full["accreditation_start_date"] = pd.NA
df_probable_full["approval_date"] = pd.NA
df_probable_full["committed_date"] = pd.NA
df_probable_full["project_status"] = "probable"

cer_cols = [
    "facility_name",
    "state",
    "capacity_mw",
    "fuel_source",
    "accreditation_code",
    "postcode",
    "accreditation_start_date",
    "approval_date",
    "committed_date",
    "project_status"
]

df_accredited_full = df_accredited_full.reindex(columns=cer_cols)
df_committed_full = df_committed_full.reindex(columns=cer_cols)
df_probable_full = df_probable_full.reindex(columns=cer_cols)

df_cer = pd.concat(
    [df_accredited_full, df_committed_full, df_probable_full],
    ignore_index=True
)

print(df_cer.shape)
print(df_cer.columns.tolist())
display(df_cer.head())
print(df_cer.info())

(131, 10)
['facility_name', 'state', 'capacity_mw', 'fuel_source', 'accreditation_code', 'postcode', 'accreditation_start_date', 'approval_date', 'committed_date', 'project_status']

,facility_name,state,capacity_mw,fuel_source,accreditation_code,postcode,accreditation_start_date,approval_date,committed_date,project_status
0,DONS FORT - SOLAR W SGU - QLD,QLD,0.421,Solar,SRPXQLO8,4660,21/10/2025,6/01/2026,NaN,accredited
1,Mintus Coles - Solar w SGU- NSW,NSW,0.19,Solar,SRPYNSK0,2153,9/12/2025,6/01/2026,NaN,accredited
2,Ventora - Acacia Ridge - Solar - QLD,QLD,0.162,Solar,SRPXQLP1,4110,17/11/2025,6/01/2026,NaN,accredited
3,Bayside Aged Care - Solar - Morisset - NSW,NSW,0.14,Solar,SRPYNSK3,2264,16/12/2025,8/01/2026,NaN,accredited
4,Matrix Composites and Engineering Pty Ltd - So...,WA,0.85,Solar,SRPVWAQ0,6166,17/12/2025,8/01/2026,NaN,accredited

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   facility_name             131 non-null    object
 1   state                     131 non-null    object
 2   capacity_mw               131 non-null    object
 3   fuel_source               131 non-null    object
 4   accreditation_code        36 non-null     object
 5   postcode                  36 non-null     object
 6   accreditation_start_date  36 non-null     object
 7   approval_date             36 non-null     object
 8   committed_date            36 non-null     object
 9   project_status            131 non-null    object
dtypes: object(10)
memory usage: 10.4+ KB
None

## Clean Data

### EDA

In [114]:
# NGER
print(df_nger.columns.tolist())
print(df_nger.head())

['Reporting Entity', 'Facility Name', 'Type', 'State', 'Electricity Production GJ', 'Electricity Production MWh', 'Total Scope 1 Emissions t CO2 e', 'Total Scope 2 Emissions t CO2 e', 'Total Emissions t CO2 e', 'Emission Intensity t CO2 e MWh', 'Grid Connected', 'Grid', 'Primary Fuel', 'Important Notes', 'year', 'Controlling corporation']
                 Reporting Entity              Facility Name Type State  \
0  ACCIONA ENERGY OCEANIA PTY LTD  Cathedral Rocks Wind Farm    F    SA
1  ACCIONA ENERGY OCEANIA PTY LTD          Gunning Wind Farm    F   NSW
2  ACCIONA ENERGY OCEANIA PTY LTD    Mt Gellibrand Wind Farm    F   VIC
3  ACCIONA ENERGY OCEANIA PTY LTD           Waubra Wind Farm    F   VIC
4  ACCIONA ENERGY OCEANIA PTY LTD            Corporate Total    C     -

   Electricity Production GJ  Electricity Production MWh  \
0                   555151.0                    154209.0
1                   636185.0                    176718.0
2                  1086174.0                    301715.0
3                  2414107.0                    670585.0
4                  4691617.0                   1303227.0

   Total Scope 1 Emissions t CO2 e  Total Scope 2 Emissions t CO2 e  \
0                             50.0                             95.0
1                             45.0                            143.0
2                             49.0                            308.0
3                            139.0                            452.0
4                            283.0                            998.0

   Total Emissions t CO2 e  Emission Intensity t CO2 e MWh Grid Connected  \
0                      145                             0.0             On
1                      188                             0.0             On
2                      357                             0.0             On
3                      591                             0.0             On
4                     1281                             NaN              -

  Grid Primary Fuel Important Notes  year Controlling corporation
0  NEM         Wind               -  2020                     NaN
1  NEM         Wind               -  2020                     NaN
2  NEM         Wind               -  2020                     NaN
3  NEM         Wind               -  2020                     NaN
4    -            -               -  2020                     NaN

### Clean NGER

In [115]:
df_nger_clean = df_nger.copy()

df_nger_clean.columns = (
    df_nger_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_", regex=True)
    .str.strip("_")
)

text_cols = [
    "reporting_entity",
    "facility_name",
    "type",
    "state",
    "grid_connected",
    "grid",
    "primary_fuel",
    "important_notes",
    "controlling_corporation"
]

for col in text_cols:
    if col in df_nger_clean.columns:
        df_nger_clean[col] = df_nger_clean[col].where(
            df_nger_clean[col].isna(),
            df_nger_clean[col].astype(str).str.strip()
        )

df_nger_clean = df_nger_clean.replace({
    "-": pd.NA,
    "": pd.NA,
    "nan": pd.NA,
    "None": pd.NA
})

numeric_cols = [
    "year",
    "electricity_production_gj",
    "electricity_production_mwh",
    "total_scope_1_emissions_t_co2_e",
    "total_scope_2_emissions_t_co2_e",
    "total_emissions_t_co2_e",
    "emission_intensity_t_co2_e_mwh"
]

for col in numeric_cols:
    if col in df_nger_clean.columns:
        df_nger_clean[col] = (
            df_nger_clean[col]
            .astype(str)
            .str.replace(",", "", regex=False)
            .replace("nan", pd.NA)
        )
        df_nger_clean[col] = pd.to_numeric(df_nger_clean[col], errors="coerce")

if "year" in df_nger_clean.columns:
    df_nger_clean["year"] = df_nger_clean["year"].astype("Int64")

if "state" in df_nger_clean.columns:
    df_nger_clean["state"] = df_nger_clean["state"].where(
        df_nger_clean["state"].isna(),
        df_nger_clean["state"].str.upper().str.strip()
    )

df_nger_clean["is_summary"] = df_nger_clean["type"] == "C"

df_nger_clean = df_nger_clean.drop(
    columns=[c for c in ["important_notes"] if c in df_nger_clean.columns]
)

df_nger_clean = df_nger_clean.drop_duplicates(
    subset=["facility_name", "year"]
)

print(df_nger_clean.shape)
print(df_nger_clean.columns.tolist())
print(df_nger_clean.isna().sum())
display(df_nger_clean.head())
print(df_nger_clean.info())

df_nger_clean.to_csv("cleaned/cleaned_nger.csv", index=False)

(4866, 16)
['reporting_entity', 'facility_name', 'type', 'state', 'electricity_production_gj', 'electricity_production_mwh', 'total_scope_1_emissions_t_co2_e', 'total_scope_2_emissions_t_co2_e', 'total_emissions_t_co2_e', 'emission_intensity_t_co2_e_mwh', 'grid_connected', 'grid', 'primary_fuel', 'year', 'controlling_corporation', 'is_summary']
reporting_entity                    401
facility_name                         3
type                                  3
state                                13
electricity_production_gj             3
electricity_production_mwh            3
total_scope_1_emissions_t_co2_e      46
total_scope_2_emissions_t_co2_e     162
total_emissions_t_co2_e               0
emission_intensity_t_co2_e_mwh       62
grid_connected                       13
grid                                 13
primary_fuel                         13
year                                  0
controlling_corporation            4465
is_summary                            0
dtype: int64

,reporting_entity,facility_name,type,state,electricity_production_gj,electricity_production_mwh,total_scope_1_emissions_t_co2_e,total_scope_2_emissions_t_co2_e,total_emissions_t_co2_e,emission_intensity_t_co2_e_mwh,grid_connected,grid,primary_fuel,year,controlling_corporation,is_summary
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,555151.0,154209.0,50.0,95.0,145,0.0,On,NEM,Wind,2020,NaN,False
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,636185.0,176718.0,45.0,143.0,188,0.0,On,NEM,Wind,2020,NaN,False
2,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1086174.0,301715.0,49.0,308.0,357,0.0,On,NEM,Wind,2020,NaN,False
3,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2414107.0,670585.0,139.0,452.0,591,0.0,On,NEM,Wind,2020,NaN,False
4,ACCIONA ENERGY OCEANIA PTY LTD,Corporate Total,C,<NA>,4691617.0,1303227.0,283.0,998.0,1281,NaN,<NA>,<NA>,<NA>,2020,NaN,True

<class 'pandas.core.frame.DataFrame'>
Index: 4866 entries, 0 to 5940
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   reporting_entity                 4465 non-null   object
 1   facility_name                    4863 non-null   object
 2   type                             4863 non-null   object
 3   state                            4853 non-null   object
 4   electricity_production_gj        4863 non-null   float64
 5   electricity_production_mwh       4863 non-null   float64
 6   total_scope_1_emissions_t_co2_e  4820 non-null   float64
 7   total_scope_2_emissions_t_co2_e  4704 non-null   float64
 8   total_emissions_t_co2_e          4866 non-null   int64
 9   emission_intensity_t_co2_e_mwh   4804 non-null   float64
 10  grid_connected                   4853 non-null   object
 11  grid                             4853 non-null   object
 12  primary_fuel                     4853 non-null   object
 13  year                             4866 non-null   Int64
 14  controlling_corporation          401 non-null    object
 15  is_summary                       4866 non-null   bool
dtypes: Int64(1), bool(1), float64(5), int64(1), object(8)
memory usage: 617.8+ KB
None

### Clean CER

In [116]:
df_cer_clean = df_cer.copy()

# 1. 列名统一（保险）
df_cer_clean.columns = (
    df_cer_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_", regex=True)
    .str.strip("_")
)

# 2. 文本清洗
text_cols = ["facility_name", "state", "fuel_source", "project_status"]

for col in text_cols:
    if col in df_cer_clean.columns:
        df_cer_clean[col] = df_cer_clean[col].where(
            df_cer_clean[col].isna(),
            df_cer_clean[col].astype(str).str.strip()
        )

# 3. state 统一
df_cer_clean["state"] = df_cer_clean["state"].str.upper().str.strip()

# 4. capacity 转 numeric
df_cer_clean["capacity_mw"] = (
    df_cer_clean["capacity_mw"]
    .astype(str)
    .str.replace(",", "", regex=False)
)
df_cer_clean["capacity_mw"] = pd.to_numeric(df_cer_clean["capacity_mw"], errors="coerce")

# 5. 日期统一（自动识别两种格式）
date_cols = [
    "accreditation_start_date",
    "approval_date",
    "committed_date"
]

for col in date_cols:
    if col in df_cer_clean.columns:
        df_cer_clean[col] = pd.to_datetime(df_cer_clean[col], errors="coerce")

# 6. 删除明显没用列（可选）
df_cer_clean = df_cer_clean.drop(columns=[
    c for c in ["postcode"] if c in df_cer_clean.columns
])

# 7. 去重
df_cer_clean = df_cer_clean.drop_duplicates()

# 查看结果
print(df_cer_clean.shape)
print(df_cer_clean.dtypes)
display(df_cer_clean.head())

df_cer_clean.to_csv("cleaned/cleaned_cer.csv", index=False)

(131, 9)
facility_name                       object
state                               object
capacity_mw                        float64
fuel_source                         object
accreditation_code                  object
accreditation_start_date    datetime64[ns]
approval_date               datetime64[ns]
committed_date              datetime64[ns]
project_status                      object
dtype: object

/var/folders/k7/sg_jf0m55vl97mk7lyd5y98m0000gn/T/ipykernel_56806/348629992.py:42: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_cer_clean[col] = pd.to_datetime(df_cer_clean[col], errors="coerce")
/var/folders/k7/sg_jf0m55vl97mk7lyd5y98m0000gn/T/ipykernel_56806/348629992.py:42: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_cer_clean[col] = pd.to_datetime(df_cer_clean[col], errors="coerce")

,facility_name,state,capacity_mw,fuel_source,accreditation_code,accreditation_start_date,approval_date,committed_date,project_status
0,DONS FORT - SOLAR W SGU - QLD,QLD,0.421,Solar,SRPXQLO8,2025-10-21,2026-06-01,NaT,accredited
1,Mintus Coles - Solar w SGU- NSW,NSW,0.190,Solar,SRPYNSK0,2025-12-09,2026-06-01,NaT,accredited
2,Ventora - Acacia Ridge - Solar - QLD,QLD,0.162,Solar,SRPXQLP1,2025-11-17,2026-06-01,NaT,accredited
3,Bayside Aged Care - Solar - Morisset - NSW,NSW,0.140,Solar,SRPYNSK3,2025-12-16,2026-08-01,NaT,accredited
4,Matrix Composites and Engineering Pty Ltd - So...,WA,0.850,Solar,SRPVWAQ0,2025-12-17,2026-08-01,NaT,accredited

### Clean AbS

In [117]:
df_abs_clean = df_abs.copy()

df_abs_clean.columns = (
    df_abs_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w]+", "_", regex=True)
    .str.strip("_")
)

drop_cols = [
    "dataflow",
    "regiontype_region_type",
    "frequency_frequency",
    "unit_mult_unit_of_multiplier",
    "obs_status_observation_status",
    "obs_comment_observation_comment"
]

df_abs_clean = df_abs_clean.drop(columns=[c for c in drop_cols if c in df_abs_clean.columns])

df_abs_clean["state"] = (
    df_abs_clean["asgs_2021_region"]
    .astype(str)
    .str.replace(r"^\d+:\s*", "", regex=True)
    .str.strip()
)

state_map = {
    "New South Wales": "NSW",
    "Victoria": "VIC",
    "Queensland": "QLD",
    "South Australia": "SA",
    "Western Australia": "WA",
    "Tasmania": "TAS",
    "Northern Territory": "NT",
    "Australian Capital Territory": "ACT",
    "Other Territories": "OT"
}

df_abs_clean["state"] = df_abs_clean["state"].map(state_map)

df_abs_clean["year"] = pd.to_numeric(
    df_abs_clean["time_period_time_period"],
    errors="coerce"
).astype("Int64")

df_abs_clean["obs_value"] = (
    df_abs_clean["obs_value"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .replace("nan", pd.NA)
)
df_abs_clean["obs_value"] = pd.to_numeric(df_abs_clean["obs_value"], errors="coerce")

df_abs_clean = df_abs_clean.drop(columns=[
    c for c in ["asgs_2021_region"] if c in df_abs_clean.columns
])

print(df_abs_clean.shape)
print(df_abs_clean.columns.tolist())
print(df_abs_clean["state"].value_counts(dropna=False))
display(df_abs_clean.head())

df_abs_clean.to_csv("cleaned/cleaned_abs.csv", index=False)

(7117, 6)
['measure_data_item', 'time_period_time_period', 'obs_value', 'unit_measure_unit_of_measure', 'state', 'year']
state
TAS    801
SA     801
ACT    801
WA     801
NT     801
VIC    801
QLD    801
NSW    801
OT     709
Name: count, dtype: int64

,measure_data_item,time_period_time_period,obs_value,unit_measure_unit_of_measure,state,year
0,LAND: Land area (ha),2021,6801753.9,HA: Hectares,TAS,2021
1,ERP_F_33: Estimated resident population:Female...,2019,6.2,PCT: Percent,SA,2019
2,ERP_F_33: Estimated resident population:Female...,2020,6.3,PCT: Percent,SA,2020
3,ERP_F_33: Estimated resident population:Female...,2021,6.4,PCT: Percent,SA,2021
4,ERP_F_33: Estimated resident population:Female...,2022,6.4,PCT: Percent,SA,2022

In [118]:
df_abs_wide = df_abs_clean.pivot_table(
    index=["state", "year"],
    columns="measure_data_item",
    values="obs_value",
    aggfunc="first"
).reset_index()

df_abs_wide.columns.name = None

df_abs_wide.columns = [
    col.split(":")[0].lower() if isinstance(col, str) else col
    for col in df_abs_wide.columns
]

print(df_abs_wide.shape)
print(df_abs_wide.columns.tolist()[:20])
display(df_abs_wide.head())

df_abs_wide.to_csv("cleaned/cleaned_abs_wide.csv", index=False)

(79, 234)
['state', 'year', 'bd_2', 'bd_3', 'bd_4', 'bd_5', 'erp_17', 'erp_18', 'erp_19', 'erp_21', 'erp_22', 'erp_23', 'erp_f_10', 'erp_f_11', 'erp_f_12', 'erp_f_13', 'erp_f_14', 'erp_f_15', 'erp_f_16', 'erp_f_17']

,state,year,bd_2,bd_3,bd_4,bd_5,erp_17,erp_18,erp_19,erp_21,...,ing_volwp2,ing_wa1,ing_wa2,ing_yr12c3p1,ing_yr12c3p2,ing_yr12c3p3,land,pension_3,pension_4,pension_5
0,ACT,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACT,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.9,NaN,NaN,504.0,77.4,651.0,NaN,NaN,NaN,NaN
2,ACT,2018,5374.0,1.63,2127.0,5.2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACT,2019,5520.0,1.61,2033.0,5.2,68.4,298244.0,34.4,184.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,1242.0,288.0
4,ACT,2020,5368.0,1.48,2162.0,4.8,68.2,303346.0,34.6,188.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.0,1143.0,264.0

### join data

In [119]:
# ============================================================
# Merge latest cleaned tables into one big denormalised table
# Use:
#   - df_nger_clean
#   - df_cer_clean
#   - df_abs_wide
# Keep all attributes, do not worry about table size
# ============================================================

import pandas as pd

# -----------------------------
# Step 1: copy cleaned tables
# -----------------------------
nger_big = df_nger_clean.copy()
cer_big = df_cer_clean.copy()
abs_big = df_abs_wide.copy()

# -----------------------------
# Step 2: helper to find columns safely
# -----------------------------
def find_first_existing(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    raise KeyError(f"None of these columns exist: {candidates}")

# -----------------------------
# Step 3: identify key columns
# -----------------------------
# NGER
nger_state_col = find_first_existing(nger_big, ["state", "State"])
nger_year_col = find_first_existing(nger_big, ["year", "Year"])

# CER
cer_state_col = find_first_existing(cer_big, ["state", "State"])

# ABS wide
abs_state_col = find_first_existing(abs_big, ["state", "State"])
abs_year_col = find_first_existing(abs_big, ["year", "Year"])

# -----------------------------
# Step 4: build merge keys
# -----------------------------
# NGER keys
nger_big["merge_state"] = nger_big[nger_state_col].astype(str).str.upper().str.strip()
nger_big["merge_year"] = pd.to_numeric(nger_big[nger_year_col], errors="coerce").astype("Int64")

# CER keys
cer_big["merge_state"] = cer_big[cer_state_col].astype(str).str.upper().str.strip()

# build CER merge_year from available date columns
cer_big["merge_year"] = pd.NA

if "committed_date" in cer_big.columns:
    cer_big["merge_year"] = pd.to_datetime(cer_big["committed_date"], errors="coerce").dt.year

if "approval_date" in cer_big.columns:
    cer_big["merge_year"] = cer_big["merge_year"].fillna(
        pd.to_datetime(cer_big["approval_date"], errors="coerce").dt.year
    )

if "accreditation_start_date" in cer_big.columns:
    cer_big["merge_year"] = cer_big["merge_year"].fillna(
        pd.to_datetime(cer_big["accreditation_start_date"], errors="coerce").dt.year
    )

cer_big["merge_year"] = pd.to_numeric(cer_big["merge_year"], errors="coerce").astype("Int64")

# ABS wide keys
abs_big["merge_state"] = abs_big[abs_state_col].astype(str).str.upper().str.strip()
abs_big["merge_year"] = pd.to_numeric(abs_big[abs_year_col], errors="coerce").astype("Int64")

# -----------------------------
# Step 5: add row ids
# -----------------------------
nger_big["nger_row_id"] = range(1, len(nger_big) + 1)
cer_big["cer_row_id"] = range(1, len(cer_big) + 1)
abs_big["abs_row_id"] = range(1, len(abs_big) + 1)

# -----------------------------
# Step 6: prefix columns to preserve all attributes clearly
# -----------------------------
def prefix_non_key_columns(df, prefix, key_cols):
    df = df.copy()
    rename_map = {}
    for col in df.columns:
        if col not in key_cols:
            rename_map[col] = f"{prefix}_{col}"
    return df.rename(columns=rename_map)

key_cols = ["merge_state", "merge_year"]

nger_pref = prefix_non_key_columns(nger_big, "nger", key_cols)
cer_pref  = prefix_non_key_columns(cer_big,  "cer",  key_cols)
abs_pref  = prefix_non_key_columns(abs_big,  "abs",  key_cols)

# -----------------------------
# Step 7: full outer join NGER + CER
# -----------------------------
df_big_1 = nger_pref.merge(
    cer_pref,
    on=["merge_state", "merge_year"],
    how="outer"
)

print("After NGER + CER merge:", df_big_1.shape)

# -----------------------------
# Step 8: full outer join with ABS wide
# -----------------------------
df_one_big_table = df_big_1.merge(
    abs_pref,
    on=["merge_state", "merge_year"],
    how="left"
)

print("Final one big table shape:", df_one_big_table.shape)

# -----------------------------
# Step 9: rename merge keys back to normal names
# -----------------------------
df_one_big_table = df_one_big_table.rename(columns={
    "merge_state": "state",
    "merge_year": "year"
})

# Put keys at the front
front_cols = ["state", "year"]
other_cols = [c for c in df_one_big_table.columns if c not in front_cols]
df_one_big_table = df_one_big_table[front_cols + other_cols]

display(df_one_big_table.head())

After NGER + CER merge: (6130, 29)
Final one big table shape: (6130, 264)

,state,year,nger_reporting_entity,nger_facility_name,nger_type,nger_state,nger_electricity_production_gj,nger_electricity_production_mwh,nger_total_scope_1_emissions_t_co2_e,nger_total_scope_2_emissions_t_co2_e,...,abs_ing_wa1,abs_ing_wa2,abs_ing_yr12c3p1,abs_ing_yr12c3p2,abs_ing_yr12c3p3,abs_land,abs_pension_3,abs_pension_4,abs_pension_5,abs_abs_row_id
0,<NA>,2017,ACCIONA ENERGY OCEANIA PTY. LTD.,Corporate Total,C,<NA>,2767186.0,768663.0,175.0,1363.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,<NA>,2018,ACCIONA ENERGY OCEANIA PTY. LTD.,Corporate Total,C,<NA>,3474683.0,965190.0,224.0,1329.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,<NA>,2019,Acciona Energy Oceania Pty. Ltd.,Corporate Total,C,<NA>,4330919.0,1203033.0,211.0,2173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,<NA>,2019,Grand Total,<NA>,<NA>,<NA>,811909812.0,225530504.0,164349333.0,1691651.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,<NA>,2020,ACCIONA ENERGY OCEANIA PTY LTD,Corporate Total,C,<NA>,4691617.0,1303227.0,283.0,998.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
# ============================================================
# Check final merged big table
# ============================================================

print("=== one big table info ===")
print(df_one_big_table.info())

print("\n=== distinct states ===")
print(sorted(df_one_big_table["state"].dropna().astype(str).unique().tolist()))

print("\n=== distinct years ===")
print(sorted(df_one_big_table["year"].dropna().astype(int).unique().tolist())[:20])

print("\n=== rows containing NGER records ===")
if "nger_nger_row_id" in df_one_big_table.columns:
    print(df_one_big_table["nger_nger_row_id"].notna().sum())

print("\n=== rows containing CER records ===")
if "cer_cer_row_id" in df_one_big_table.columns:
    print(df_one_big_table["cer_cer_row_id"].notna().sum())

print("\n=== rows containing ABS records ===")
if "abs_abs_row_id" in df_one_big_table.columns:
    print(df_one_big_table["abs_abs_row_id"].notna().sum())

=== one big table info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6130 entries, 0 to 6129
Columns: 264 entries, state to abs_abs_row_id
dtypes: Int64(3), datetime64[ns](3), float64(242), object(16)
memory usage: 12.4+ MB
None

=== distinct states ===
['<NA>', 'ACT', 'NAN', 'NSW', 'NT', 'QLD', 'SA', 'TAS', 'VIC', 'WA']

=== distinct years ===
[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

=== rows containing NGER records ===
6019

=== rows containing CER records ===
2192

=== rows containing ABS records ===
5603

In [121]:
# ============================================================
# Export final one big table
# ============================================================

df_one_big_table.to_csv("cleaned/one_big_table_all_attributes.csv", index=False)
print("Exported: cleaned/one_big_table_all_attributes.csv")

Exported: cleaned/one_big_table_all_attributes.csv

### Data Augmentation

In [122]:
from tqdm import tqdm
import requests
from urllib.parse import quote
import time

In [123]:
api_key = "AIzaSyDD1Vvj_fzwINPcGqiNASVp98toVDDhC_c"

def query_facility(facility, state, max_retries=3):
    """
    Query Google Geocoding API v4 for one facility.
    Returns a dictionary instead of only (lat, lng).
    """
    address = f"{facility}, {state}, Australia"
    encoded_address = quote(address, safe="")
    url = f"https://geocode.googleapis.com/v4/geocode/address/{encoded_address}"

    headers = {
        "X-Goog-Api-Key": api_key
    }

    for attempt in range(max_retries):
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status()
            data = response.json()

            if "results" in data and len(data["results"]) > 0:
                top = data["results"][0]
                location = top["location"]

                return {
                    "geo_query": address,
                    "latitude": location.get("latitude"),
                    "longitude": location.get("longitude"),
                    "place_id": top.get("placeId"),
                    "formatted_address": top.get("formattedAddress"),
                    "geocode_status": "OK"
                }

            return {
                "geo_query": address,
                "latitude": None,
                "longitude": None,
                "place_id": None,
                "formatted_address": None,
                "geocode_status": "NO_RESULT"
            }

        except requests.exceptions.RequestException as e:
            print(f"⚠️ Attempt {attempt + 1} failed: {e}")
            time.sleep(0.5)

    return {
        "geo_query": address,
        "latitude": None,
        "longitude": None,
        "place_id": None,
        "formatted_address": None,
        "geocode_status": "REQUEST_ERROR"
    }

In [124]:
df_nger_geo = df_nger_clean.copy()

# 如果你们列名已经统一成小写 snake_case
facility_col = "facility_name"
state_col = "state"
type_col = "type" if "type" in df_nger_geo.columns else None

# 只保留真正设施
if type_col is not None:
    df_nger_geo = df_nger_geo[df_nger_geo[type_col] == "F"].copy()

df_nger_geo = df_nger_geo.dropna(subset=[facility_col, state_col]).copy()

df_nger_geo = df_nger_geo[
    ~df_nger_geo[facility_col].astype(str).str.contains(
        "Corporate Total|Grand Total|Total",
        case=False,
        na=False
    )
].copy()

print("Rows eligible for geocoding:", len(df_nger_geo))
df_nger_geo[[facility_col, state_col]].head()

Rows eligible for geocoding: 4835

                facility_name state
0   Cathedral Rocks Wind Farm    SA
1           Gunning Wind Farm   NSW
2     Mt Gellibrand Wind Farm   VIC
3            Waubra Wind Farm   VIC
5  Adani Rugby Run Solar Farm   QLD

构造唯一 query

In [125]:
df_nger_geo["geo_query"] = (
    df_nger_geo[facility_col].astype(str).str.strip()
    + ", "
    + df_nger_geo[state_col].astype(str).str.strip()
    + ", Australia"
)

unique_facilities = (
    df_nger_geo[[facility_col, state_col, "geo_query"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

print("Unique facility queries:", len(unique_facilities))
unique_facilities.head()

Unique facility queries: 846

,facility_name,state,geo_query
0,Cathedral Rocks Wind Farm,SA,"Cathedral Rocks Wind Farm, SA, Australia"
1,Gunning Wind Farm,NSW,"Gunning Wind Farm, NSW, Australia"
2,Mt Gellibrand Wind Farm,VIC,"Mt Gellibrand Wind Farm, VIC, Australia"
3,Waubra Wind Farm,VIC,"Waubra Wind Farm, VIC, Australia"
4,Adani Rugby Run Solar Farm,QLD,"Adani Rugby Run Solar Farm, QLD, Australia"

In [126]:
import os
import json

cache_path = "cleaned/nger_google_geocode_cache.json"

if os.path.exists(cache_path):
    with open(cache_path, "r", encoding="utf-8") as f:
        geocode_cache = json.load(f)
else:
    geocode_cache = {}

print("Existing cache size:", len(geocode_cache))

Existing cache size: 0

批量查询 Google API

In [ ]:
from tqdm import tqdm

# 先只测试前 5 条
unique_facilities = unique_facilities.copy()
#测试成功删除上条代码，下面的 test_facilities 替换成 unique_facilities 就可以对所有设施进行 geocoding
results = []

for _, row in tqdm(unique_facilities.iterrows(), total=len(unique_facilities), desc="NGER geocoding"):
    result = query_facility(row[facility_col], row[state_col])
    result[facility_col] = row[facility_col]
    result[state_col] = row[state_col]
    results.append(result)

df_nger_geocode_results = pd.DataFrame(results)

print(df_nger_geocode_results["geocode_status"].value_counts(dropna=False))
df_nger_geocode_results.head()

NGER geocoding:  14%|█▍        | 120/846 [01:31<08:48,  1.37it/s]

In [ ]:
df_nger_augmented = df_nger_geo.merge(
    df_nger_geocode_results[
        [facility_col, state_col, "latitude", "longitude", "place_id", "formatted_address", "geocode_status"]
    ],
    on=[facility_col, state_col],
    how="left"
)

print("Augmented NGER shape:", df_nger_augmented.shape)
df_nger_augmented.head()

Augmented NGER shape: (4835, 22)

,reporting_entity,facility_name,type,state,electricity_production_gj,electricity_production_mwh,total_scope_1_emissions_t_co2_e,total_scope_2_emissions_t_co2_e,total_emissions_t_co2_e,emission_intensity_t_co2_e_mwh,...,primary_fuel,year,controlling_corporation,is_summary,geo_query,latitude,longitude,place_id,formatted_address,geocode_status
0,ACCIONA ENERGY OCEANIA PTY LTD,Cathedral Rocks Wind Farm,F,SA,555151.0,154209.0,50.0,95.0,145,0.0,...,Wind,2020,NaN,False,"Cathedral Rocks Wind Farm, SA, Australia",-34.865051,135.596742,ChIJxUQr6dNSqmoRoCd9mT-Z1-Y,"Sleaford SA 5607, Australia",OK
1,ACCIONA ENERGY OCEANIA PTY LTD,Gunning Wind Farm,F,NSW,636185.0,176718.0,45.0,143.0,188,0.0,...,Wind,2020,NaN,False,"Gunning Wind Farm, NSW, Australia",-34.690562,149.427009,ChIJQWYzdN7cFmsRGdZ3LbCG8xU,"Gunning NSW 2581, Australia",OK
2,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1086174.0,301715.0,49.0,308.0,357,0.0,...,Wind,2020,NaN,False,"Mt Gellibrand Wind Farm, VIC, Australia",-38.257966,143.799570,ChIJtVGxGFyf02oR1E9wzP1YXS0,"450 Mooleric Rd, Birregurra VIC 3242, Australia",OK
3,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2414107.0,670585.0,139.0,452.0,591,0.0,...,Wind,2020,NaN,False,"Waubra Wind Farm, VIC, Australia",-37.394639,143.638601,ChIJjRMVspBs0WoRncGnVM7olVA,"275 Harrisons Rd, Waubra VIC 3352, Australia",OK
4,ADANI RENEWABLE ASSET HOLDINGS PTY LTD,Adani Rugby Run Solar Farm,F,QLD,589185.0,163662.0,0.0,0.0,0,0.0,...,Solar,2020,NaN,False,"Adani Rugby Run Solar Farm, QLD, Australia",-22.575197,144.084793,ChIJ_dxieiTf1GsRmb4SdiLQ8vU,"Queensland, Australia",OK

In [ ]:
df_nger_augmented.to_csv("cleaned/cleaned_nger_augmented_google.csv", index=False)
print("Exported: cleaned/cleaned_nger_augmented_google.csv")

Exported: cleaned/cleaned_nger_augmented_google.csv

In [ ]:
# ============================================================
# Store cleaned / augmented data into DuckDB with spatial extension
# Create source tables + one big table named: full_table
# ============================================================

import duckdb
import pandas as pd
import os

# -----------------------------
# 0. make output folder
# -----------------------------
os.makedirs("database", exist_ok=True)

# -----------------------------
# 1. connect DuckDB
# -----------------------------
db_path = "database/energy_project.duckdb"
con = duckdb.connect(db_path)

# -----------------------------
# 2. install + load spatial extension
# -----------------------------
con.execute("INSTALL spatial;")
con.execute("LOAD spatial;")

# -----------------------------
# 3. select dataframes
# -----------------------------
if "df_nger_augmented" in globals():
    nger_df = df_nger_augmented.copy()
elif "df_nger_clean" in globals():
    nger_df = df_nger_clean.copy()
elif "df_nger" in globals():
    nger_df = df_nger.copy()
else:
    raise ValueError("No NGER dataframe found.")

if "df_cer_clean" in globals():
    cer_df = df_cer_clean.copy()
elif "df_cer" in globals():
    cer_df = df_cer.copy()
else:
    raise ValueError("No CER dataframe found.")

if "df_abs_wide" in globals():
    abs_df = df_abs_wide.copy()
elif "df_abs_clean" in globals():
    abs_df = df_abs_clean.copy()
elif "df_abs" in globals():
    abs_df = df_abs.copy()
else:
    raise ValueError("No ABS dataframe found.")

# -----------------------------
# 4. clean column names
# -----------------------------
def clean_columns(df):
    df = df.copy()
    df.columns = (
        pd.Index(df.columns)
        .str.strip()
        .str.lower()
        .str.replace(r"[^\w]+", "_", regex=True)
        .str.strip("_")
    )
    return df

nger_df = clean_columns(nger_df)
cer_df = clean_columns(cer_df)
abs_df = clean_columns(abs_df)

# -----------------------------
# 5. standardise state/year
# -----------------------------
def std(df):
    df = df.copy()
    if "state" in df.columns:
        df["state"] = df["state"].astype(str).str.upper().str.strip()
    if "year" in df.columns:
        df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
    return df

nger_df = std(nger_df)
cer_df = std(cer_df)
abs_df = std(abs_df)

# -----------------------------
# 6. register
# -----------------------------
con.register("nger_df_view", nger_df)
con.register("cer_df_view", cer_df)
con.register("abs_df_view", abs_df)

# -----------------------------
# 7. drop tables
# -----------------------------
for tbl in ["nger_facilities", "cer_projects", "abs_state_year",
            "full_table", "nger_tmp", "cer_tmp", "abs_tmp"]:
    con.execute(f"DROP TABLE IF EXISTS {tbl};")

# -----------------------------
# 8. create source tables
# -----------------------------
con.execute("CREATE TABLE nger_facilities AS SELECT * FROM nger_df_view;")
con.execute("CREATE TABLE cer_projects AS SELECT * FROM cer_df_view;")
con.execute("CREATE TABLE abs_state_year AS SELECT * FROM abs_df_view;")

# -----------------------------
# 9. add id
# -----------------------------
con.execute("""
CREATE OR REPLACE TABLE nger_facilities AS
SELECT row_number() OVER () AS nger_id, * FROM nger_facilities;
""")

con.execute("""
CREATE OR REPLACE TABLE cer_projects AS
SELECT row_number() OVER () AS cer_id, * FROM cer_projects;
""")

con.execute("""
CREATE OR REPLACE TABLE abs_state_year AS
SELECT row_number() OVER () AS abs_id, * FROM abs_state_year;
""")

# -----------------------------
# 10. spatial column for NGER
# -----------------------------
cols = [r[1] for r in con.execute("PRAGMA table_info('nger_facilities')").fetchall()]

if "latitude" in cols and "longitude" in cols:
    con.execute("""
    CREATE OR REPLACE TABLE nger_facilities AS
    SELECT *,
    CASE WHEN longitude IS NOT NULL AND latitude IS NOT NULL
         THEN ST_Point(CAST(longitude AS DOUBLE), CAST(latitude AS DOUBLE))
         ELSE NULL END AS geom
    FROM nger_facilities;
    """)

# -----------------------------
# 11. temp tables (keys)
# -----------------------------
con.execute("""
CREATE TABLE nger_tmp AS
SELECT *, UPPER(TRIM(state)) AS merge_state,
       CAST(year AS INTEGER) AS merge_year
FROM nger_facilities;
""")

con.execute("""
CREATE TABLE cer_tmp AS
SELECT *,
    UPPER(TRIM(state)) AS merge_state,
    COALESCE(
        YEAR(TRY_CAST(committed_date AS DATE)),
        YEAR(TRY_CAST(approval_date AS DATE)),
        YEAR(TRY_CAST(accreditation_start_date AS DATE))
    ) AS merge_year
FROM cer_projects;
""")

con.execute("""
CREATE TABLE abs_tmp AS
SELECT *, UPPER(TRIM(state)) AS merge_state,
       CAST(year AS INTEGER) AS merge_year
FROM abs_state_year;
""")

# -----------------------------
# 12. ONE BIG TABLE
# -----------------------------
con.execute("""
CREATE TABLE full_table AS
SELECT
    COALESCE(n.merge_state, c.merge_state, a.merge_state) AS state,
    COALESCE(n.merge_year, c.merge_year, a.merge_year) AS year,

    n.* EXCLUDE (merge_state, merge_year),
    c.* EXCLUDE (merge_state, merge_year),
    a.* EXCLUDE (merge_state, merge_year)

FROM nger_tmp n
FULL OUTER JOIN cer_tmp c
    ON n.merge_state = c.merge_state
   AND n.merge_year = c.merge_year

LEFT JOIN abs_tmp a
    ON COALESCE(n.merge_state, c.merge_state) = a.merge_state
   AND COALESCE(n.merge_year, c.merge_year) = a.merge_year;
""")

# -----------------------------
# 13. add id
# -----------------------------
con.execute("""
CREATE OR REPLACE TABLE full_table AS
SELECT row_number() OVER () AS full_id, * FROM full_table;
""")

# -----------------------------
# 14. spatial for full_table
# -----------------------------
cols = [r[1] for r in con.execute("PRAGMA table_info('full_table')").fetchall()]

if "longitude" in cols and "latitude" in cols:
    con.execute("""
    CREATE OR REPLACE TABLE full_table AS
    SELECT *,
    CASE WHEN longitude IS NOT NULL AND latitude IS NOT NULL
         THEN ST_Point(CAST(longitude AS DOUBLE), CAST(latitude AS DOUBLE))
         ELSE NULL END AS geom
    FROM full_table;
    """)

# -----------------------------
# 15. checks
# -----------------------------
print("=== tables ===")
print(con.execute("SHOW TABLES").fetchdf())

print("\n=== row counts ===")
print("nger:", con.execute("SELECT COUNT(*) FROM nger_facilities").fetchone()[0])
print("cer :", con.execute("SELECT COUNT(*) FROM cer_projects").fetchone()[0])
print("abs :", con.execute("SELECT COUNT(*) FROM abs_state_year").fetchone()[0])
print("full:", con.execute("SELECT COUNT(*) FROM full_table").fetchone()[0])

print("\n=== preview ===")
display(con.execute("SELECT * FROM full_table LIMIT 5").fetchdf())

=== tables ===
                 name
0         abs_df_view
1      abs_state_year
2             abs_tmp
3         cer_df_view
4        cer_projects
5             cer_tmp
6          full_table
7   integrated_energy
8        nger_df_view
9     nger_facilities
10           nger_tmp

=== row counts ===
nger: 4835
cer : 131
abs : 79
full: 6099

=== preview ===

,full_id,state,year,nger_id,reporting_entity,facility_name,type,state_1,electricity_production_gj,electricity_production_mwh,...,ing_wa1,ing_wa2,ing_yr12c3p1,ing_yr12c3p2,ing_yr12c3p3,land,pension_3,pension_4,pension_5,geom_1
0,1,VIC,2021,511,ACCIONA ENERGY OCEANIA PTY LTD,Mt Gellibrand Wind Farm,F,VIC,1018498.0,282916.0,...,48156.0,61.2,4167.0,72.6,5739.0,22749624.8,444.0,14958.0,5678.0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
1,2,VIC,2021,512,ACCIONA ENERGY OCEANIA PTY LTD,Waubra Wind Farm,F,VIC,2339624.0,649896.0,...,48156.0,61.2,4167.0,72.6,5739.0,22749624.8,444.0,14958.0,5678.0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
2,3,VIC,2021,514,AGL ENERGY LIMITED,Banimboola Hydro,F,VIC,7240.0,2011.0,...,48156.0,61.2,4167.0,72.6,5739.0,22749624.8,444.0,14958.0,5678.0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
3,4,VIC,2021,517,AGL ENERGY LIMITED,Bogong Power Station,F,VIC,314481.0,87356.0,...,48156.0,61.2,4167.0,72.6,5739.0,22749624.8,444.0,14958.0,5678.0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
4,5,VIC,2021,519,AGL ENERGY LIMITED,Clover Hydro,F,VIC,1481.0,411.0,...,48156.0,61.2,4167.0,72.6,5739.0,22749624.8,444.0,14958.0,5678.0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."

Done.

In [ ]:
# -----------------------------
# 15. checks
# -----------------------------
print("=== tables ===")
tables_df = con.execute("SHOW TABLES").fetchdf()
display(tables_df)

print("\n=== row counts ===")
print("nger_facilities :", con.execute("SELECT COUNT(*) FROM nger_facilities").fetchone()[0])
print("cer_projects    :", con.execute("SELECT COUNT(*) FROM cer_projects").fetchone()[0])
print("abs_state_year  :", con.execute("SELECT COUNT(*) FROM abs_state_year").fetchone()[0])
print("full_table      :", con.execute("SELECT COUNT(*) FROM full_table").fetchone()[0])

print("\n=== nger_facilities preview ===")
display(con.execute("SELECT * FROM nger_facilities LIMIT 10").fetchdf())

print("\n=== cer_projects preview ===")
display(con.execute("SELECT * FROM cer_projects LIMIT 10").fetchdf())

print("\n=== abs_state_year preview ===")
display(con.execute("SELECT * FROM abs_state_year LIMIT 10").fetchdf())

print("\n=== full_table preview ===")
display(con.execute("SELECT * FROM full_table LIMIT 10").fetchdf())
con.close()
print("\nDone.")

=== tables ===

ConnectionException: Connection Error: Connection already closed!